apiVersion: v2
name: keycloak
description: Customized Keycloak container
icon: https://avatars3.githubusercontent.com/u/15859888
type: application
version: 0.2.2
appVersion: 1.16.0

dependencies:
- name: keycloakx
  version: "2.2.1"
  repository: "https://codecentric.github.io/helm-charts"