{{- $svcPathType := default .Values.keycloak.service.pathType "ImplementationSpecific"  -}}
{{- $labels := include "keycloak.labels" . -}}
{{- if .Values.keycloak.ingress}}
{{- range $key, $value := .Values.keycloak.ingress.appgw }}
{{- if $value.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-{{$key}}
  labels:
    {{- $labels | trim | nindent 4 }}
  {{- with $value.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $value.className }}
  ingressClassName: {{ $value.className }}
  {{- end }}
{{- if $value.tls }}
  tls:
  {{- range $value.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $value.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: {{ $svcPathType }} 
            backend:
              service:
                name: keycloak-http
                port:
                  number: 80
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

