apiVersion: v2
name: yms-keycloak
description: Customized Keycloak container
icon: https://avatars3.githubusercontent.com/u/15859888
type: application
version: 0.9.6
appVersion: 1.20.3

dependencies:
- name: keycloak
  version: "9.x"
  repository: "https://codecentric.github.io/helm-charts"
